version: "3.8"

services:
  dante:
    image: avt0x/dante:1.4.3
    ports:
      - "1080:1080"
    volumes:
      - ./data:/etc/dante
    env_file:
      - .env
    tmpfs:
      - /run
    restart: unless-stopped
